### ISSUE TITLE
customdata type should not be string

### ISSUE THREAD

**Issue by displague** [t0mk/gometal#1]
README.md:
> I tried to put it together and in client.go there's code that should list projects. However, there probably some inconsitencies in the API definition, for instance the customdata parameter doesn't work out-of-the-box:

I'm not sure if this is an OAS3 option or if it is OAS2/Swagger2 compatible, but we might be able to fix this by removing `type: string` from the customdata fields in the spec. `type` is optional in OAS3, and when omitted the field is understood to be _any_ type.

https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.21 

For the response value, we know that it may be nullable, boolean, string, int, or a map. I think the undefined type will work for this case too.

**Comment by t0mk** [comment]
fixed in #4 by pathcing the customdata type to `object`. @displague please consider closing this.

It should still be fixed in the API JSON though.

**Comment by displague** [comment]
To get the `interface{}` type, we may have to remove `"type":` for `customdata` fields.

**Comment by displague** [comment]
I'll send along to the upstream any patches we identify.

**Comment by t0mk** [comment]
> To get the interface{} type, we may have to remove "type": for customdata fields.

`"type": "object"` seems to work as well

**Comment by displague** [comment]
I was worried that this would not generate a client that can support values of `"1"` (or the other types we saw in https://github.com/packethost/packngo/pull/225#issuecomment-744594881).  The generated type is `interface{}`, so it seems ok.
